" enable indent plugin
filetype plugin indent on

" reload if the file changes
set autoread

" run gofmt on save
au BufWritePost *.go !goimports -w %

" show tabs as characters
set list
set listchars=tab:>-
