cd /home/joseph/

source /home/joseph/.git_prompt.sh
source /home/joseph/.git-completion.bash

export GOROOT=/usr/local/go
export GOPATH=$HOME/go

export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

alias ls='ls -FGlh'
alias docker='sudo docker'
alias git='hub'

if [ ! -f /secrets/gitcredentials ]; then
    echo "warning - git credentials not found"
fi

if [ ! -f /secrets/private-gpg ]; then
    echo "warning - private gpg key not found"
fi

if [ ! -f /secrets/public-gpg ]; then
    echo "warning - public gpg key not found"
fi

if [ -f /secrets/private-gpg ] && [ -f /secrets/public-gpg ] ; then
    if ! gpg --list-keys | grep -q 'salisbury.joseph@gmail.com' ; then
        gpg --import /secrets/private-gpg
        gpg --import /secrets/public-gpg
    fi
fi

# Set the terminal size - this can be an issue when running as a Kubernetes pod.
# See https://wiki.archlinux.org/index.php/working_with_the_serial_console#Resizing_a_terminal
stty cols 238 rows 60

PS1='\[\e[1;36m\]\u\e[0m\] on \[\e[1;36m\]\H\e[0m\] at \[\e[1;36m\]\t\e[0m\] in \[\e[1;36m\]\w\e[0m\]$(__git_ps1 " (%s)")\n$ '

