cd /home/joseph/

source /home/joseph/.git_prompt.sh

export PATH="$PATH:$HOME/bin"
export GOPATH="$HOME/go"
export GOOS="linux"
export GOARCH="amd64"

alias ls='ls -FGlh'

PS1='\[\e[1;36m\]\t\e[0m\] \[\e[1;36m\]\H\e[0m\] \[\e[1;36m\]\w\e[0m\]$(__git_ps1 " (%s)")\n$ '